# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pi_sample_rcpp <- function(n) {
    .Call('testing_pi_sample_rcpp', PACKAGE = 'testing', n)
}

pi_sample_rcpp2 <- function(n) {
    .Call('testing_pi_sample_rcpp2', PACKAGE = 'testing', n)
}

hello_world <- function() {
    .Call('testing_hello_world', PACKAGE = 'testing')
}

hello_world2 <- function(n) {
    .Call('testing_hello_world2', PACKAGE = 'testing', n)
}

hello_world3 <- function(n) {
    .Call('testing_hello_world3', PACKAGE = 'testing', n)
}

hello_world4 <- function(n) {
    .Call('testing_hello_world4', PACKAGE = 'testing', n)
}

